wallpaper {

monitor = DP-1

#Blue Firewatch
# path = ~/Pictures/Wallpapers/firewatch-background.png

#Orange Firewatch
path = ~/Pictures/Wallpapers/firewatch-minimal-jx-2560x1440.jpg


fit_mode = cover


}

wallpaper {

monitor = HDMI-A-1
#Blue Firewatch
# path = ~/Pictures/Wallpapers/firewatch-1920.png

#Orange Firewatch
path = ~/Pictures/Wallpapers/firewatch-minimal-jx-1920x1080.jpg
fit_mode = cover

}

splash = false
