wallpaper {

monitor = DP-1

#Blue Firewatch
# path = ~/Pictures/Wallpapers/firewatch-background.png

#Orange Firewatch
#path = ~/Pictures/Wallpapers/firewatch-minimal-jx-2560x1440.jpg

#Random Other One
#path = ~/Pictures/Wallpapers/wp7585344-autumn-2560x1440-wallpapers.jpg

#Minecraft Nightime
# path = ~/Pictures/Wallpapers/MCNightimeWallpaper.jpg

#Minecraft Sunset
path = ~/Pictures/Wallpapers/ww3.png

fit_mode = cover


}

wallpaper {

monitor = HDMI-A-1
#Blue Firewatch
# path = ~/Pictures/Wallpapers/firewatch-1920.png

#Orange Firewatch
#path = ~/Pictures/Wallpapers/firewatch-minimal-jx-1920x1080.jpg

#Random Other one
#path = ~/Pictures/Wallpapers/11zon_resized.jpg

#Minecraft Nightime
# path = ~/Pictures/Wallpapers/MCNight1920.jpg

#Minecraft Sunset
path = ~/Pictures/Wallpapers/ww3.png

fit_mode = cover
}

splash = false
